spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  #JPA ??
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          format_sql: true
          show_sql: true

  # h2
  h2:
    console:
      enabled: true
      path: /h2-console

  # jwt
  jwt:
    header: Authorization
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    token-validity-in-seconds: 86400
  #jsp?? ?? ??? ?? ?? ???? spring-boot-devtools
  devtools:
    livereload:
      enabled: true

  logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
  server:
    port: 8080