DROP TABLE USER;
DROP TABLE AUTHORITY;
DROP TABLE USER_AUTHORITY;
CREATE TABLE USER(USER_ID LONG PRIMARY KEY AUTO_INCREMENT, USERNAME VARCHAR(20), PASSWORD VARCHAR(70), NICKNAME VARCHAR(20), ACTIVATED boolean);
CREATE TABLE AUTHORITY(AUTHORITY_NAME VARCHAR(20));
CREATE TABLE USER_AUTHORITY(USER_ID long, AUTHORITY_NAME VARCHAR(20));

INSERT INTO USER (USER_ID, USERNAME, PASSWORD, NICKNAME, ACTIVATED) VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 1);

INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (1, 'ROLE_USER');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (1, 'ROLE_ADMIN');